#!/bin/bash
rm -rf AnyKernel3
rm -rf Kneip*
rm -rf out
git clone https://github.com/zclkkk/AnyKernel3.git
cd AnyKernel3
rm -rf .git
cd ..
BOARD=cepheus
CLANG_DIR=/home/zclkkk/clang
export KBUILD_BUILD_USER="zclkkk"
export KBUILD_BUILD_HOST="Server"
export PATH=${CLANG_DIR}/bin:${PATH}
args="                  ARCH=arm64 \
                        O=../out \
                        CC=clang \
                        AR=llvm-ar \
                        NM=llvm-nm \
                        OBJCOPY=llvm-objcopy \
                        OBJDUMP=llvm-objdump \
                        STRIP=llvm-strip \
                        LD=ld.lld \
                        HOSTCC=clang \
                        HOSTLD=ld.lld \
                        HOSTAR=llvm-ar \
                        HOSTCXX=clang++ \
                        CLANG_TRIPLE=aarch64-linux-gnu- \
                        CROSS_COMPILE=aarch64-linux-gnu- \
                        CROSS_COMPILE_ARM32=arm-linux-gnueabi- "
cd msm-4.14
make ${args} ${BOARD}_defconfig
make -j64 ${args}
cd ..
cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
cp out/arch/arm64/boot/dtbo.img AnyKernel3/
cd AnyKernel3
VERSION="$(cat ../msm-4.14/arch/arm64/configs/${BOARD}_defconfig | grep "CONFIG_LOCALVERSION\=" | sed -r 's/.*"(.+)".*/\1/' | sed 's/^.//')"
7z a -mx9 ${VERSION}.zip *
zipalign -v 4 ${VERSION}.zip ../${VERSION}_${BOARD}.zip
cd ..
transfer trs ${VERSION}_${BOARD}.zip
rm -rf AnyKernel3
rm -rf Kneip*
